"""Initial: Create players, bots, conversation_contexts, compression_logs tables

Revision ID: 55201c59d143
Revises: 
Create Date: 2026-01-01 20:26:12.680274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55201c59d143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False, comment='Bot 名称'),
    sa.Column('personality', sa.Text(), nullable=False, comment='人格设定 (System Prompt)'),
    sa.Column('owner_uuid', sa.String(length=36), nullable=True, comment='当前主人 UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_name'), 'bots', ['name'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Minecraft UUID'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='当前游戏名'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_uuid'), 'players', ['uuid'], unique=True)
    op.create_table('conversation_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('raw_buffer', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='L0 原始对话缓冲'),
    sa.Column('episodic_memory', sa.Text(), nullable=False, comment='L1 情景记忆'),
    sa.Column('core_memory', sa.Text(), nullable=False, comment='L2 核心记忆'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_compressed_at', sa.DateTime(), nullable=True),
    sa.Column('compression_count', sa.Integer(), nullable=False, comment='压缩次数'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_contexts_bot_id'), 'conversation_contexts', ['bot_id'], unique=False)
    op.create_index(op.f('ix_conversation_contexts_player_id'), 'conversation_contexts', ['player_id'], unique=False)
    op.create_table('compression_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('compression_type', sa.String(length=10), nullable=False, comment='L0_L1 或 L1_L2'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='输入 Token 数'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='输出 Token 数'),
    sa.Column('before_snapshot', sa.Text(), nullable=False, comment='压缩前内容快照'),
    sa.Column('after_snapshot', sa.Text(), nullable=False, comment='压缩后内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['conversation_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compression_logs_context_id'), 'compression_logs', ['context_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compression_logs_context_id'), table_name='compression_logs')
    op.drop_table('compression_logs')
    op.drop_index(op.f('ix_conversation_contexts_player_id'), table_name='conversation_contexts')
    op.drop_index(op.f('ix_conversation_contexts_bot_id'), table_name='conversation_contexts')
    op.drop_table('conversation_contexts')
    op.drop_index(op.f('ix_players_uuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_bots_name'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
