"""Add player online status and bot ownership fields

Revision ID: 7d8d61dac115
Revises: 55201c59d143
Create Date: 2026-01-02 16:22:06.917140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8d61dac115'
down_revision: Union[str, Sequence[str], None] = '55201c59d143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('owner_name', sa.String(length=16), nullable=True, comment='当前主人名称'))
    op.add_column('bots', sa.Column('skin_url', sa.Text(), nullable=True, comment='皮肤 URL'))
    op.add_column('bots', sa.Column('claimed_at', sa.DateTime(), nullable=True, comment='认领时间'))
    op.add_column('bots', sa.Column('auto_spawn', sa.Boolean(), nullable=False, server_default='true', comment='主人上线时自动生成'))
    op.create_index(op.f('ix_bots_owner_uuid'), 'bots', ['owner_uuid'], unique=False)
    op.add_column('players', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='false', comment='当前是否在线'))
    op.add_column('players', sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_login')
    op.drop_column('players', 'is_online')
    op.drop_index(op.f('ix_bots_owner_uuid'), table_name='bots')
    op.drop_column('bots', 'auto_spawn')
    op.drop_column('bots', 'claimed_at')
    op.drop_column('bots', 'skin_url')
    op.drop_column('bots', 'owner_name')
    # ### end Alembic commands ###
