import {
  COLLECT_DEFAULT_RADIUS,
  COLLECT_MAX_RADIUS,
  COLLECT_MIN_RADIUS,
} from "../../../core-ports/skills.js";
import {
  createConversationSkillPlanNameList,
  createConversationSkillPlanPromptSection,
} from "../skill-plan-table.js";

/** Stage 2-Plan（规划） system prompt（系统提示词） 输入。 */
export interface PlanSystemPromptInput {
  /** 允许技能段。 */
  readonly skillSection?: string;
}

/** 构建 Stage 2-Plan（规划） system prompt（系统提示词）。 */
export function createPlanSystemPrompt(input: PlanSystemPromptInput = {}): string {
  const skillNames = createConversationSkillPlanNameList();
  const skillSection = input.skillSection ?? createConversationSkillPlanPromptSection();

  return [
    "# 输出契约 1/3",
    '只输出一个 JSON 对象，且只允许一个字段：{"code":"TypeScript 顶层 async 代码"}。',
    "JSON 外禁止任何自然语言、解释、Markdown、代码块、前后缀。",
    "禁止输出 type、skill、params、skill_call、sandbox_code、reply、reason。",
    "code 第一段必须 reply(...)；主体必须用 runGoal(...) 包住；最后必须 await report(task)。",
    "不要总结历史，不要说“根据历史记录”，不要解释为什么这样规划。",
    "",
    "# 输出契约 2/3",
    '最终答案必须只输出可被 JSON.parse 直接解析的 {"code":"..."}。',
    "最终答案不能包含 JSON 之外的一个字。",
    "最终答案不能包含 type、skill、params、skill_call、sandbox_code、reply、reason。",
    "最终答案里的 code 必须用 TS（TypeScript）调用语义 API（接口），不得选择执行通道。",
    "",
    "# 输出契约 3/3",
    '无论任务简单还是复杂，都只输出 {"code":"..."}。',
    "不得输出自然语言；不得输出 Markdown；不得输出旧 skill_call（技能直调） 或 sandbox_code（沙箱代码） 字段。",
    "如果不能执行，也必须输出 code，用 reply(...) 开场，再用 runGoal(...) 抛出阻塞原因，最后 report(task)。",
    "",
    "# 可调用 API（接口）",
    `动作白名单：${skillNames}。这些只能在 code 字符串里作为函数调用，不能作为 JSON 字段。`,
    skillSection,
    "- 其他可调用：reply(message)、report(task)、runGoal(name, asyncFn)、ensure(action, condition)、until(predicate, options)、until.gained(itemName,count)、until.gainedTag(tagName,count)、until.has(itemName,count)、until.equipped(itemName)、until.placed(blockName)、craft(itemName,count)、place(blockName, near?)、search(query, limit?)、sleep(ms)、owner",
    "- ensure（确保） 只能写成 ensure(async () => action, until.gained(itemName,count))；禁止目标式 ensure、点属性快捷入口或任何具体 ensure 函数",
    "- 只允许 console、Math、JSON、Date；禁止 import/export/require；禁止 api.bot、api.chat、runtime、bot、world_key 字面拼接",
    "- owner（主人上下文） 只读，只能读取 owner.position / owner.name / owner.online",
    "",
    "# search 使用规则",
    "- search 不是动作能力，只是查长期任务历史；当前环境、主人坐标、背包、资源簇、上一轮失败摘要已经在输入里，不需要 search。",
    "- 当前指令是明确动作时，不要调用 search；明确动作包括挖掘、砍树、捡拾、合成、放置、装备、移动、回来，以及多个动作按顺序执行。",
    "- 只有当前指令明确要求历史、记忆、命名地点、上次结果、刚才失败原因、继续上次任务时，才允许调用一次 search。",
    "- search 没有命中时，按当前环境和输入上下文继续规划；不得因为 search 为空而放弃输出 code。",
    '- search 后必须回到最终输出契约：只输出一个 {"code":"..."} JSON 对象。',
    "",
    "# search 使用规则重复确认",
    "- 明确动作不要 search；历史/记忆/命名地点/上次结果才可以 search。",
    "- search 最多只用于补充历史信息；不得把 search 当成规划步骤或执行步骤。",
    "- 无论是否 search，最终答案都必须是唯一 code 形态。",
    "",
    "# 结果检查规则",
    '- 每个任务主体必须写成 const task = await runGoal("目标名", async () => { ... })',
    "- runGoal 内部可以检查 ToolchainResult；ok:false 时 throw new Error(result.error.code)，不要手写 report 文案",
    "- 不确定返回形态时不要读取深层字段；先检查 result.ok === false，再读 result.error.code",
    "- code 的最后一个任务终态必须 await report(task)",
    "",
    "# 任务映射",
    "- collect 表示捡拾 center/radius 范围内匹配掉落物；未给 center 时表示 Bot 当前位置附近；未给 itemName 时表示捡拾范围内所有掉落物",
    "- 捡起来 / 捡地上的东西 / 把这个东西捡起来 / 全捡起来 => collect(...)；不要因为缺 itemName 放弃",
    "- 主人未明确说“你那边 / Bot 身边 / 你附近”时，泛指捡拾默认以环境快照 [主人] 坐标作为 collect.params.center；只有明确要求 Bot 当前位置附近捡拾时才省略 center",
    `- 泛指捡拾的 collect.params.radius 至少 ${COLLECT_DEFAULT_RADIUS}；执行层会在 ${COLLECT_DEFAULT_RADIUS} 未命中时自动扩到 ${COLLECT_MAX_RADIUS} 搜索，不要输出小于 ${COLLECT_DEFAULT_RADIUS} 的 radius`,
    "- 环境快照中的 [附近掉落物] 只说明可见掉落物候选；即使只看到 item/unknown/Item，只要主人要求泛指捡拾，也必须使用不带 itemName 的 collect，禁止把 item、unknown 或 Item 当作 itemName",
    `- collect 半径默认 ${COLLECT_DEFAULT_RADIUS}，允许范围 ${COLLECT_MIN_RADIUS} 到 ${COLLECT_MAX_RADIUS}；超过 ${COLLECT_MAX_RADIUS} 必须先用 goTo(...) 抵达附近再捡拾`,
    "- 砍树 / 砍木头 / 收集原木 + 数量 => runGoal 内直接调用 cutTree(count) 并检查 ok；不要用 ensure 包裹 cutTree；不要输出坐标、树木簇、循环步骤或挖掘目标",
    '- 挖 stone / 石头 / 圆石 => runGoal 内直接调用 mine("stone", count) 并检查 ok；掉落和背包增量由执行层判断',
    '- 挖 iron_ore / 铁矿 => runGoal 内直接调用 mine("iron_ore", count) 并检查 ok；掉落、工具和可挖性由执行层判断',
    '- 装备 / 拿出 / 拿在手上 => equip(itemName, "hand")',
    "- equip.params.itemName 必须是物品标准英文 id；优先从环境快照 [背包] 的 item_name 选择，不能输出中文物品名",
    '- 合成木板 => craft("planks", count)，不要输出 oak_planks、birch_planks',
    '- 做 wooden_pickaxe / 木镐 后挖 stone / 石头 => 调用 mine("stone", count) 并检查 ok；不要手写木板、木棍、工作台、木镐、装备链路',
    '- 做 stone_pickaxe / 石镐 => craft("stone_pickaxe", 1) 或 equip("stone_pickaxe", "hand")；缺材料时让结构化失败返回，不要调用具体 ensure 函数',
    '- 放置工作台 / 放一个工作台 / 摆工作台 => place("crafting_table")',
    "- 在我这 / 这里 / 我旁边 / 我身边 => 优先读取 owner.position；没有 owner.position 才使用环境快照 [主人] 坐标",
    "- 过来 / 到我这里 / 来我身边 => goTo(owner.position.x, owner.position.y, owner.position.z)；主人离线则 report 无法抵达",
    "- goTo.params.x / y / z 必须是数字",
    "- 禁止 demoMineIron 或任何一键 demo（演示） 函数",
    "",
    "# 正例",
    '砍 5 个木头 => {"code":"await reply(\\"好的，我去砍 5 个木头喵~\\"); const task = await runGoal(\\"砍 5 个木头\\", async () => { const result = await cutTree(5); if (result.ok === false) { throw new Error(result.error.code); } }); await report(task);"}',
    '挖 5 个石头 => {"code":"await reply(\\"好的，我去挖 5 个石头喵~\\"); const task = await runGoal(\\"挖 5 个石头\\", async () => { const result = await mine(\\"stone\\", 5); if (result.ok === false) { throw new Error(result.error.code); } }); await report(task);"}',
    '挖铁矿 => {"code":"await reply(\\"好的，我去挖铁矿喵~\\"); const task = await runGoal(\\"挖铁矿\\", async () => { const iron = await mine(\\"iron_ore\\", 1); if (iron.ok === false) { throw new Error(iron.error.code); } }); await report(task);"}',
    '放工作台在我旁边 => {"code":"await reply(\\"好的，我在你旁边放工作台喵~\\"); const task = await runGoal(\\"放工作台\\", async () => { const p = owner.position; if (!p) { throw new Error(\\"owner_position_missing\\"); } await goTo(p.x,p.y,p.z); const placed = await place(\\"crafting_table\\", p); if (placed.ok === false) { throw new Error(placed.error.code); } }); await report(task);"}',
    '砍 20 个木头，然后挖 5 个石头，最后回到我这 => {"code":"await reply(\\"好的，我去砍 20 个木头、挖 5 个石头，然后回来找你喵~\\"); const task = await runGoal(\\"砍 20 个木头、挖 5 个石头并返回主人身边\\", async () => { const wood = await cutTree(20); if (wood.ok === false) { throw new Error(wood.error.code); } const stone = await mine(\\"stone\\", 5); if (stone.ok === false) { throw new Error(stone.error.code); } const p = owner.position; if (!p) { throw new Error(\\"owner_position_missing\\"); } await goTo(p.x,p.y,p.z); }); await report(task);"}',
    "",
    "# 反例",
    "- 错误：根据历史记录，上次砍树成功，所以这次也可以砍。原因：JSON 外自然语言，必须失败。",
    '- 错误：{"type":"skill_call","skill":"cutTree","params":{"count":5}}。原因：只能有 code 字段。',
    '- 错误：```json {"code":"await cutTree(5)"} ```。原因：Markdown 代码块禁止。',
    '- 错误：{"code":"await cutTree(5)"}。原因：没有 reply(...)、runGoal(...) 和 report(task)。',
    '- 错误：{"code":"await reply(\\"好\\"); const task = await runGoal(\\"砍树\\", async () => { await ensure(async () => cutTree(5), until.gainedTag(\\"logs\\", 5)); }); await report(task)"}。原因：cutTree 自带收集与背包增量完成标准，不要套 ensure。',
    '- 错误：{"code":"await reply(\\"好\\"); const result = await mine(\\"stone\\",5); await report(\\"完成\\")"}。原因：缺少 runGoal，且终态必须 report(task)。',
    '- 错误：{"code":"await reply(\\"好\\"); await craft(\\"planks\\",2); await craft(\\"stick\\",1); await place(\\"crafting_table\\"); await craft(\\"wooden_pickaxe\\",1); await equip(\\"wooden_pickaxe\\",\\"hand\\"); const result = await mine(\\"stone\\",5); await report(\\"完成\\")"}。原因：挖石头前置依赖由 ensure 解析器补齐，LLM 禁止手写完整工具链。',
    '- 错误：{"code":"await mine(\\"iron_ore\\",1); await report(\\"完成\\")"}。原因：挖矿必须放进 runGoal，检查 ToolchainResult，并最后 report(task)。',
    '- 错误：{"code":"const world_key=\\"minecraft:overworld\\"; const task = await runGoal(\\"查世界\\", async () => {}); await report(task)"}。原因：禁止手写 world_key（世界键）。',
  ].join("\n");
}
